// ============================================================
// IGWEMP — Mock Data Store
// Rich Phase 1 demo data for development without Supabase
// ============================================================

import type {
  WorkQueueItem, Section, Office, DelegationOfAuthority,
  NotificationDelivery, HierarchyLevel
} from '../types';

// ─── Hierarchy Levels ─────────────────────────────────────────
export const MOCK_HIERARCHY_LEVELS: HierarchyLevel[] = [
  {
    id: 'lv-01', level_id: 'lv-01', tenant_id: 'sed-tenant-001', level_code: 'DIRECTORATE',
    level_name: 'Directorate', sort_order: 1, parent_level_id: null,
    allowed_office_types: ['DIRECTORATE'],
    created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'lv-02', level_id: 'lv-02', tenant_id: 'sed-tenant-001', level_code: 'DISTRICT',
    level_name: 'District (CEO Office)', sort_order: 2, parent_level_id: 'lv-01',
    allowed_office_types: ['DISTRICT'],
    created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'lv-03', level_id: 'lv-03', tenant_id: 'sed-tenant-001', level_code: 'ZONE',
    level_name: 'Zone (ZEO Office)', sort_order: 3, parent_level_id: 'lv-02',
    allowed_office_types: ['ZONE'],
    created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'lv-04', level_id: 'lv-04', tenant_id: 'sed-tenant-001', level_code: 'SCHOOL',
    level_name: 'School', sort_order: 4, parent_level_id: 'lv-03',
    allowed_office_types: ['SCHOOL'],
    created_at: '2026-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z',
  },
];

// ─── CEO Office ───────────────────────────────────────────────
export const MOCK_CEO_OFFICE: Office = {
  id: 'office-ceo-anantnag',
  office_id: 'office-ceo-anantnag',
  tenant_id: 'sed-tenant-001',
  office_code: 'CEO-ANT',
  office_name: 'CEO Office Anantnag',
  level_id: 'lv-02',
  parent_office_id: 'office-dir-001',
  path: 'dir.ceo_ant',
  office_subtype: 'DISTRICT',
  is_active: true,
  address: 'DC Complex, Anantnag, J&K — 192101',
  deleted_at: null,
  created_at: '2026-01-01T00:00:00Z',
  updated_at: '2026-01-01T00:00:00Z',
};

// ─── Sections ─────────────────────────────────────────────────
export const MOCK_SECTIONS: Section[] = [
  {
    id: 'sec-est-001', section_id: 'sec-est-001',
    tenant_id: 'sed-tenant-001',
    office_id: 'office-ceo-anantnag',
    section_type: 'ESTABLISHMENT',
    section_name: 'Establishment Section',
    head_user_id: 'user-officer-001',
    queue_enabled: true,
    is_active: true,
    deleted_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sec-acad-001', section_id: 'sec-acad-001',
    tenant_id: 'sed-tenant-001',
    office_id: 'office-ceo-anantnag',
    section_type: 'ACADEMIC',
    section_name: 'Academic Section',
    head_user_id: 'user-officer-002',
    queue_enabled: true,
    is_active: true,
    deleted_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sec-acct-001', section_id: 'sec-acct-001',
    tenant_id: 'sed-tenant-001',
    office_id: 'office-ceo-anantnag',
    section_type: 'ACCOUNTS',
    section_name: 'Accounts Section',
    head_user_id: 'user-officer-003',
    queue_enabled: true,
    is_active: true,
    deleted_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sec-infra-001', section_id: 'sec-infra-001',
    tenant_id: 'sed-tenant-001',
    office_id: 'office-ceo-anantnag',
    section_type: 'INFRASTRUCTURE',
    section_name: 'Infrastructure Section',
    head_user_id: null,
    queue_enabled: false,
    is_active: true,
    deleted_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'sec-sch-001', section_id: 'sec-sch-001',
    tenant_id: 'sed-tenant-001',
    office_id: 'office-ceo-anantnag',
    section_type: 'SCHOLARSHIP',
    section_name: 'Scholarship Section',
    head_user_id: 'user-officer-004',
    queue_enabled: true,
    is_active: true,
    deleted_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
];

// ─── Work Queue Items ─────────────────────────────────────────
const now = new Date();
const overdue2days = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString();
const overdue5days = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString();
const todayEnd = new Date(now.setHours(23, 59, 0, 0)).toISOString();
const in2days = new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString();
const in5days = new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString();
const in10days = new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_WORK_QUEUE_ITEMS: WorkQueueItem[] = [
  {
    item_id: 'wq-001',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-001',
    item_type: 'ATR',
    priority: 'OVERDUE',
    status: 'IN_PROGRESS',
    due_at: overdue5days,
    picked_up_by: 'user-ceo-001',
    picked_up_at: overdue5days,
    delegation_context: null,
    created_at: overdue5days,
    updated_at: overdue5days,
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-001',
      tenant_id: 'sed-tenant-001',
      order_id: 'ord-001',
      instance_id: 'wf-001',
      case_type: 'SURVEY_ATR',
      assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001',
      parent_case_id: null,
      status: 'IN_PROGRESS',
      deadline_at: overdue5days,
      version_number: 1,
      created_at: overdue5days,
      updated_at: overdue5days,
    },
  },
  {
    item_id: 'wq-002',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-002',
    item_type: 'VERIFICATION',
    priority: 'OVERDUE',
    status: 'IN_PROGRESS',
    due_at: overdue2days,
    picked_up_by: 'user-ceo-001',
    picked_up_at: overdue2days,
    delegation_context: null,
    created_at: overdue2days,
    updated_at: overdue2days,
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-002',
      tenant_id: 'sed-tenant-001',
      order_id: 'ord-002',
      instance_id: 'wf-002',
      case_type: 'VERIFICATION',
      assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001',
      parent_case_id: null,
      status: 'IN_PROGRESS',
      deadline_at: overdue2days,
      version_number: 1,
      created_at: overdue2days,
      updated_at: overdue2days,
    },
  },
  {
    item_id: 'wq-003',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-003',
    item_type: 'APPROVAL',
    priority: 'DUE_TODAY',
    status: 'SUBMITTED',
    due_at: todayEnd,
    picked_up_by: null,
    picked_up_at: null,
    delegation_context: null,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-003',
      tenant_id: 'sed-tenant-001',
      order_id: 'ord-003',
      instance_id: 'wf-003',
      case_type: 'INSPECTION_APPROVAL',
      assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001',
      parent_case_id: null,
      status: 'PENDING_APPROVAL',
      deadline_at: todayEnd,
      version_number: 1,
      created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      updated_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
  },
  {
    item_id: 'wq-004',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-004',
    item_type: 'CASE',
    priority: 'DUE_TODAY',
    status: 'IN_PROGRESS',
    due_at: todayEnd,
    picked_up_by: 'user-ceo-001',
    picked_up_at: new Date(Date.now() - 3600000).toISOString(),
    delegation_context: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-004',
      tenant_id: 'sed-tenant-001',
      order_id: 'ord-004',
      instance_id: 'wf-004',
      case_type: 'ENROLLMENT_CENSUS',
      assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001',
      parent_case_id: null,
      status: 'IN_PROGRESS',
      deadline_at: todayEnd,
      version_number: 1,
      created_at: new Date(Date.now() - 3600000).toISOString(),
      updated_at: new Date(Date.now() - 3600000).toISOString(),
    },
  },
  {
    item_id: 'wq-005',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-005',
    item_type: 'ATR',
    priority: 'DUE_THIS_WEEK',
    status: 'IN_PROGRESS',
    due_at: in2days,
    picked_up_by: 'user-ceo-001',
    picked_up_at: new Date(Date.now() - 86400000).toISOString(),
    delegation_context: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-005', tenant_id: 'sed-tenant-001',
      order_id: 'ord-005', instance_id: 'wf-005',
      case_type: 'TRANSFER_ATR', assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001', parent_case_id: null,
      status: 'IN_PROGRESS', deadline_at: in2days,
      version_number: 1, created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date(Date.now() - 86400000).toISOString(),
    },
  },
  {
    item_id: 'wq-006',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-006',
    item_type: 'CASE',
    priority: 'DUE_THIS_WEEK',
    status: 'IN_PROGRESS',
    due_at: in5days,
    picked_up_by: 'user-ceo-001',
    picked_up_at: new Date(Date.now() - 86400000).toISOString(),
    delegation_context: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-006', tenant_id: 'sed-tenant-001',
      order_id: 'ord-006', instance_id: 'wf-006',
      case_type: 'INFRASTRUCTURE_REPORT', assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001', parent_case_id: null,
      status: 'IN_PROGRESS', deadline_at: in5days,
      version_number: 1, created_at: new Date(Date.now() - 86400000).toISOString(),
      updated_at: new Date(Date.now() - 86400000).toISOString(),
    },
  },
  {
    item_id: 'wq-007',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'USER',
    assignee_id: 'user-ceo-001',
    case_id: 'case-007',
    item_type: 'CASE',
    priority: 'UPCOMING',
    status: 'UNASSIGNED',
    due_at: in10days,
    picked_up_by: null,
    picked_up_at: null,
    delegation_context: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    assignee_name: 'Abdul Karim (CEO)',
    case: {
      case_id: 'case-007', tenant_id: 'sed-tenant-001',
      order_id: 'ord-007', instance_id: 'wf-007',
      case_type: 'PROFILE_UPDATE', assigned_to_type: 'USER',
      assigned_to_id: 'user-ceo-001', parent_case_id: null,
      status: 'OPEN', deadline_at: in10days,
      version_number: 1, created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  },
];

// ─── Active Delegation [ADJ-04] ───────────────────────────────
export const MOCK_ACTIVE_DELEGATION: DelegationOfAuthority = {
  id: 'del-001',
  delegation_id: 'del-001',
  tenant_id: 'sed-tenant-001',
  delegated_by: 'user-dir-001',
  delegated_to: 'user-ceo-001',
  delegation_type: 'APPROVAL_ONLY',
  scope_of_authority: {
    modules: ['cases', 'atrs', 'orders'],
    actions: ['approve', 'return'],
    office_scope: 'own_office',
    max_case_value: null,
    excluded_types: [],
  },
  effective_from: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  effective_to: new Date(Date.now() + 13 * 24 * 60 * 60 * 1000).toISOString(),
  reason: 'Director on official tour to Jammu for 15 days',
  issuing_order_id: null,
  status: 'ACTIVE',
  approved_by: null,
  revoked_by: null,
  revoked_at: null,
  revocation_reason: null,
  created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  delegator: {
    id: 'user-dir-001',
    user_id: 'user-dir-001',
    tenant_id: 'sed-tenant-001',
    party_id: 'party-dir-001',
    supabase_auth_id: 'mock-dir-001',
    username: 'director.sed',
    status: 'ACTIVE',
    is_active: true,
    is_mfa_enabled: true,
    last_login_at: null,
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
    party: {
      id: 'party-dir-001',
      party_id: 'party-dir-001',
      tenant_id: 'sed-tenant-001',
      party_type: 'PERSON',
      display_name: 'Dr. Bashir Ahmad (Director)',
      first_name: 'Bashir',
      last_name: 'Ahmad',
      aadhaar_hash: null,
      aadhaar_last4: null,
      pan_hash: null,
      pan_masked: null,
      dob: null,
      gender: 'MALE',
      is_active: true,
      deleted_at: null,
      mobile: null,
      email: 'director.sed@jk.gov.in',
      created_at: '2026-01-01T00:00:00Z',
      updated_at: '2026-01-01T00:00:00Z',
    },
  },
};

// ─── Notifications ────────────────────────────────────────────
export const MOCK_NOTIFICATIONS: NotificationDelivery[] = [
  {
    delivery_id: 'notif-001',
    tenant_id: 'sed-tenant-001',
    event_id: 'evt-001',
    recipient_id: 'user-ceo-001',
    channel: 'IN_APP',
    status: 'DELIVERED',
    priority: 'URGENT',
    title: 'Case #ATR-00241 is OVERDUE',
    body: 'Survey Form ATR for GHSS Bijbehara — 5 days overdue. Immediate action required.',
    action_url: '/cases/case-001',
    delivered_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    read_at: null,
    created_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    delivery_id: 'notif-002',
    tenant_id: 'sed-tenant-001',
    event_id: 'evt-002',
    recipient_id: 'user-ceo-001',
    channel: 'IN_APP',
    status: 'DELIVERED',
    priority: 'HIGH',
    title: 'Approval Required — Inspection Report',
    body: 'Inspection Report for GHSS Sopore has been submitted and awaits your approval.',
    action_url: '/cases/case-003',
    delivered_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    read_at: null,
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    delivery_id: 'notif-003',
    tenant_id: 'sed-tenant-001',
    event_id: 'evt-003',
    recipient_id: 'user-ceo-001',
    channel: 'IN_APP',
    status: 'DELIVERED',
    priority: 'HIGH',
    title: 'Delegation Active — Acting for Dr. Bashir Ahmad',
    body: 'Approval-only delegation from Director is now active. Expires 25 Jun 2026.',
    action_url: '/delegations',
    delivered_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    delivery_id: 'notif-004',
    tenant_id: 'sed-tenant-001',
    event_id: 'evt-004',
    recipient_id: 'user-ceo-001',
    channel: 'IN_APP',
    status: 'DELIVERED',
    priority: 'NORMAL',
    title: 'New Circular — Academic Calendar 2026-27',
    body: 'Directorate of School Education has issued the Academic Calendar for 2026-27.',
    action_url: '/circulars',
    delivered_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    delivery_id: 'notif-005',
    tenant_id: 'sed-tenant-001',
    event_id: 'evt-005',
    recipient_id: 'user-ceo-001',
    channel: 'IN_APP',
    status: 'DELIVERED',
    priority: 'NORMAL',
    title: 'ATR Approved — Transfer Order ORD-00031',
    body: 'ZEO Bijbehara has approved the ATR for Transfer Order IGWEMP-SED-2026-ORD-00031.',
    action_url: '/cases/case-005',
    delivered_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    read_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Section Work Queue Items [ADJ-01] ────────────────────────
export const MOCK_SECTION_QUEUE_ITEMS: WorkQueueItem[] = [
  {
    item_id: 'sq-001',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'SECTION',
    assignee_id: 'sec-est-001',
    case_id: 'case-sq-001',
    item_type: 'CASE',
    priority: 'DUE_TODAY',
    status: 'UNASSIGNED',
    due_at: todayEnd,
    picked_up_by: null,
    picked_up_at: null,
    delegation_context: null,
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    assignee_name: 'Establishment Section',
  },
  {
    item_id: 'sq-002',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'SECTION',
    assignee_id: 'sec-est-001',
    case_id: 'case-sq-002',
    item_type: 'ATR',
    priority: 'OVERDUE',
    status: 'IN_PROGRESS',
    due_at: overdue2days,
    picked_up_by: 'user-officer-001',
    picked_up_at: new Date(Date.now() - 86400000).toISOString(),
    delegation_context: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    assignee_name: 'Establishment Section',
  },
  {
    item_id: 'sq-003',
    tenant_id: 'sed-tenant-001',
    assignee_type: 'SECTION',
    assignee_id: 'sec-est-001',
    case_id: 'case-sq-003',
    item_type: 'APPROVAL',
    priority: 'DUE_THIS_WEEK',
    status: 'SUBMITTED',
    due_at: in2days,
    picked_up_by: 'user-officer-001',
    picked_up_at: new Date(Date.now() - 3600000).toISOString(),
    delegation_context: null,
    created_at: new Date(Date.now() - 3600000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    assignee_name: 'Establishment Section',
  },
];
